---
- name: install redis-commander
  npm: name=redis-commander global=yes

- template: src=redis-commander.j2 dest=/etc/init.d/redis-commander mode=0755
  notify: restart redis-commander

- service: name=redis-commander state=running
