language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update && composer install
  - openssl aes-256-cbc -K $encrypted_d40576457a66_key -iv $encrypted_d40576457a66_iv -in config/secrets.yml.enc -out config/secrets.yml -d

script: app/kahlan
