language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  global:
    - PATH=./node_modules/.bin:$PATH

install:
  - openssl aes-256-cbc -K $encrypted_d40576457a66_key -iv $encrypted_d40576457a66_iv -in config/secrets.yml.enc -out config/secrets.yml -d
  - sudo apt-get install -y graphicsmagick
  - composer self-update && composer install
  - npm install && bower install && gulp build

notifications:
  email: false

services:
  - redis-server

script: app/kahlan
