---
- name: create blog directory
  file: path={{ blog_path }} state=directory owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} recurse=yes

- name: download ghost
  command: wget https://ghost.org/zip/ghost-latest.zip -P /tmp creates=/tmp/ghost-latest.zip

- name: extract ghost
  unarchive: src=/tmp/ghost-latest.zip dest={{ blog_path }} copy=no

- name: npm install
  command: npm install --production chdir={{ blog_path }}

- name: install theme
  git: repo=https://github.com/stevelacey/ghostium.git dest={{ blog_path }}/content/themes/ghostium

- template: src={{ item }}.sh.j2 dest={{ blog_path }}/content/{{ item }}.sh mode=0755
  with_items:
    - backup
    - restore

- command: "{{ blog_path }}/content/restore.sh creates={{ blog_path }}/content/data/ghost.db"

# - service: name=blog state=running
