---
- cron: name="joindin import"
        job="{{ app_path }}/current/app/console joindin:import:all"
        minute="{{ range((app|int-1) * 30 + 2, 59, 30 * apps|int) | join(',') }}"

- cron: name="meetup import"
        job="{{ app_path }}/current/app/console meetup:import:all"
        minute="{{ range((app|int-1) * 15 + 4, 59, 15 * apps|int) | join(',') }}"

- cron: name="twitter import"
        job="{{ app_path }}/current/app/console twitter:import:all"
        minute="{{ range((app|int-1) * 30 + 6, 59, 30 * apps|int) | join(',') }}"

- cron: name="youtube import"
        job="{{ app_path }}/current/app/console youtube:import:all"
        minute="{{ range((app|int-1) * 30 + 8, 59, 30 * apps|int) | join(',') }}"

- cron: name="invoice all" minute=0 hour=9 day=14
        job="{{ app_path }}/current/app/console invoice:all"
        month="{{ range(app|int * 1, 13, 1 * apps|int) | join(',') }}"

- script: keys.rb ubuntu phpsw
  tags: [keys]
