---
- name: add haproxy 1.6 repository
  apt_repository: repo='ppa:vbernat/haproxy-1.6'

- name: install haproxy
  apt: name=haproxy state=latest

- name: copy haproxy service file
  action: template src=haproxy.j2 dest=/etc/default/haproxy
  notify: reload haproxy

# - name: create /etc/ssl directory
#   file: path=/etc/ssl state=directory

# - name: copy ssl certificates into /etc/ssl
#   copy:
#     content: "{{ item.value }}"
#     dest: "/etc/ssl/{{ item.key }}.pem"
#     owner: root
#     group: root
#     mode: 0600
#   with_dict: "{{ ssl_certificates }}"

- name: configure /etc/haproxy/haproxy.cfg
  template:
    src: 'haproxy.cfg.j2'
    dest: '/etc/haproxy/haproxy.cfg'
  notify: reload haproxy

- service: name=haproxy state=running
