---
- name: composer install
  composer: command=install working_dir={{ app_path }}
  become: false

- name: npm install
  command: npm install --quiet
  become: false
  args:
    chdir: "{{ app_path }}"

- name: bower install
  command: bower install --quiet
  become: false
  args:
    chdir: "{{ app_path }}"

- name: gulp build
  command: gulp build
  become: false
  args:
    chdir: "{{ app_path }}"

- name: redis restore recent backup
  shell: "{{ item }}"
  with_items:
    - |
      s3cmd sync $(s3cmd ls s3://phpsw/backups/* -c /home/vagrant/.s3cfg \
       | tail -n 1 \
       | awk '{ print $4 }') /var/lib/redis/dump.rdb.gz -c /home/vagrant/.s3cfg
    - service redis stop
    - gzip -df /var/lib/redis/dump.rdb.gz
    - service redis start
    - |
      redis-cli keys \* \
       | awk '{ print $1 }' \
       | perl -pe 's/phpsw:(.*)/rename phpsw:\1 phpsw:dev:\1/g' \
       | redis-cli -x

- name: sf import all
  shell: "{{ item }}"
  with_items:
    - sf joindin:import:all
    - sf meetup:import:all
    - sf twitter:import:all
  become: false
  args:
    chdir: "{{ app_path }}"
