---
app:
  domain: phpsw.vm
  path: /home/vagrant/phpsw

nginx:
  docroot: "{{ app.path }}/web"
  servername: phpsw.vm

php:
  ppa: php5-5.6
  packages: [php5-cli, php5-intl, php5-mcrypt, php5-curl, php5-readline]

redis:
  port: '6379'

server:
  packages: [git, graphicsmagick, htop, vim, zsh]
  timezone: UTC
  locale: en_GB.UTF-8

thumbor:
  ports:
    - "8000"
    - "8001"
    - "8002"
    - "8003"
