---
- name: add ppa repository
  apt_repository: repo=ppa:ondrej/{{ php.ppa }}

- name: update apt
  apt: update_cache=yes

- name: install php5
  apt: pkg=php5 state=latest

- name: install php5-fpm
  apt: pkg=php5-fpm state=latest

- name: install php packages
  apt: pkg={{ item }} state=latest
  with_items: php.packages
  when: php.packages is defined

- include: configure.yml
- include: pecl.yml
