name: PHPSW

description: |
    Friendly PHP user group in Bristol, UK.
    We meet every month to discuss all things PHP.
    Brilliant opportunity to learn something new, share your skills, network, find a job, advertise a job, drink beer.

meetup:
    name: PHPSW
    url: http://www.meetup.com/php-sw
    urlname: php-sw
    api:
        key: ~

twitter:
    url: http://twitter.com/phpsw
    user: phpsw
