---
- name: install redis-commander
  npm: name=redis-commander global=yes

- name: configure supervisor
  template: src=supervisor.conf.j2 dest=/etc/supervisor/conf.d/redis-commander.conf
  notify:
    - reread supervisor
    - restart redis-commander

- supervisorctl: name=redis-commander state=started
