---
- name: composer install
  composer: command=install working_dir={{ app_path }}
  become: false

- name: npm install
  command: npm install --quiet
  become: false
  args:
    chdir: "{{ app_path }}"

- name: bower install
  command: bower install --quiet
  become: false
  args:
    chdir: "{{ app_path }}"

- name: gulp build
  command: gulp build
  become: false
  args:
    chdir: "{{ app_path }}"

- name: config directory
  file: path={{ app_config }} state=directory
  become: false

- name: secrets
  template: src=secrets.yml.j2 dest={{ app_config }}/secrets.yml
  become: false
  tags:
    - secrets

- name: fix secrets
  shell: "{{ item }}"
  with_items:
    - |
      perl -i'' -e 'undef $/; $_=<>; s/:\s+'"'"'(.*)\n(\s+)/: |\n\2\1\n\2/g; print' {{ app_config }}/secrets.yml
    - |
      perl -i'' -pe "s/\s+\'\n//g" {{ app_config }}/secrets.yml
    - |
      perl -i'' -0pe 's/\n{2,}/\n/g' {{ app_config }}/secrets.yml
    - |
      perl -i'' -0pe 's/(\n\w+:)/\n\1/g' {{ app_config }}/secrets.yml
  become: false
  tags:
    - secrets

- name: redis restore recent backup
  shell: "{{ item }}"
  with_items:
    - |
      s3cmd sync $(s3cmd ls s3://phpsw/backups/* -c /home/vagrant/.s3cfg \
       | tail -n 1 \
       | awk '{ print $4 }') /var/lib/redis/6379/dump.rdb.gz -c /home/vagrant/.s3cfg
    - service redis stop
    - gzip -df /var/lib/redis/6379/dump.rdb.gz
    - service redis start
    - |
      /opt/redis/bin/redis-cli keys \* \
       | awk '{ print $1 }' \
       | perl -pe 's/phpsw:(.*)/rename phpsw:\1 phpsw:dev:\1/g' \
       | /opt/redis/bin/redis-cli -x
  tags:
    - redis

- name: sf import all
  shell: "{{ item }}"
  with_items:
    - sf joindin:import:all
    - sf meetup:import:all
    - sf twitter:import:all
  become: false
  args:
    chdir: "{{ app_path }}"
