---
- name: /var/www present
  file: path=/var/www state=directory owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} recurse=yes

- name: /var/www/html absent
  file: path=/var/www/html state=absent

- name: config directory
  file: path={{ app_config }} state=directory

- name: secrets
  template: src=secrets.yml.j2 dest={{ app_config }}/secrets.yml
  tags:
    - secrets

- name: fix secrets
  shell: "{{ item }}"
  with_items:
    - |
      perl -i'' -e 'undef $/; $_=<>; s/:\s+'"'"'(.*)\n(\s+)/: |\n\2\1\n\2/g; print' {{ app_config }}/secrets.yml
    - |
      perl -i'' -pe "s/\s+\'\n//g" {{ app_config }}/secrets.yml
    - |
      perl -i'' -0pe 's/\n{2,}/\n/g' {{ app_config }}/secrets.yml
    - |
      perl -i'' -0pe 's/(\n\w+:)/\n\1/g' {{ app_config }}/secrets.yml
  become: false
  tags:
    - secrets
