---
- name: create app directory
  file: path={{ app_path }} state=directory owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} recurse=yes

- name: create avatars directory
  file: path={{ avatars_path }} state=directory owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} recurse=yes

- name: create config directory
  file: path={{ app_config }} state=directory owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }} recurse=yes

- name: delete /var/www/html
  file: path=/var/www/html state=absent

- name: install avatars
  git: repo=https://github.com/stevelacey/tweetimages-php.git dest={{ avatars_path }}

- name: secrets
  template: src=secrets.yml.j2 dest={{ app_config }}/secrets.yml
  tags:
    - secrets

- name: fix secrets
  shell: "{{ item }}"
  with_items:
    - |
      perl -i'' -e 'undef $/; $_=<>; s/:\s+'"'"'(.*)\n(\s+)/: |\n\2\1\n\2/g; print' {{ app_config }}/secrets.yml
    - |
      perl -i'' -pe "s/\s+\'\n//g" {{ app_config }}/secrets.yml
    - |
      perl -i'' -0pe 's/\n{2,}/\n/g' {{ app_config }}/secrets.yml
    - |
      perl -i'' -0pe 's/(\n\w+:)/\n\1/g' {{ app_config }}/secrets.yml
  become: false
  tags:
    - secrets
