---
- hosts: app
  gather_facts: true
  sudo: true
  vars_files:
    - vars/all.yml
  roles:
    - server
    - hostname
    - haproxy
    - nginx
    - php
    - redis
    - thumbor
    - varnish
    - xdebug
    - composer
    - node
    - app
