---
- hosts: app
  become: true
  roles:
    - server
    - hostname
    - user
    - nginx
    - php
    - redis
    - thumbor
    - varnish
    - xdebug
    - composer
    - node
    - haproxy
    - app
  vars_files:
    - secrets.yml
    - variables.yml
